# Generated by Django 3.2.16 on 2024-09-23 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('process', models.BooleanField(default=False)),
                ('local_sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usage.category')),
            ],
        ),
    ]
